[DEBUG   ] confapp.settings_manager                 + SETTINGS: pyforms.settings                  confapp.settings_[DEBUG   ] confapp.settings_manager                 + SETTINGS: pyforms_gui.setticonfapp.settings_manager - DEBUG -[DEBUG   ] confapp.settings_manager                 + SETTINGS: OpenGL.acceleratesupport - INFO - No OpenGL_acceler[INFO    ] OpenGL.acceleratesupport                 No idtrackerai_app.base_idtrackerai - INFO - Local settings file not ava[INFO   idtrackerai_app.base_idtrackerai - INFO - TENSORFLOW DEVICES: [_DeviceAttribute[INFO    ] idtrackerai_app.base_idtrackerai         TENSORFLOW DEVICES: [_DeviceAttribconfapp.settings_manager - DEBUG - + SETTINGS: pyforms_gui.resources_settings            [DEBUG   __main__.video - DEBUG - Video object init
__main__.video - DEBUG - Video(open_multiple_files=False)
__main__.video - INFO - the folder /Users/ninatubau/Desktop/session_test has been created
idtrackerai_app.base_idtrackerai - DEBUG - create Chosen_Video
__main__.video - DEBUG - Video object init
__main__.video - DEBUG - Video(open_multiple_files=False)
idtrackerai_app.base_idtrackerai - DEBUG - before init PreprocessingPreviewAPI
idtrackerai_app.base_idtrackerai - DEBUG - pre object: <idtrackerai.preprocessing_preview_api.PreprocessingPreviewAPI object at 0x156295c50>
idtrackerai_app.base_idtrackerai - DEBUG - call: init_preview
idtrackerai.preprocessing_preview_api - DEBUG - init_preview
idtrackerai.preprocessing_preview_api - DEBUG - init_preproc_parameters
idtrackerai.preprocessing_preview_api - DEBUG - init_segment_zero
idtrackerai_app.base_idtrackerai - DEBUG - call: init_preproc_parameters
idtrackerai.preprocessing_preview_api - DEBUG - init_preproc_parameters
idtrackerai_app.base_idtrackerai - DEBUG - call: segment
idtrackerai.preprocessing_preview_api - DEBUG - segment
idtrackerai.preprocessing_preview_api - DEBUG - segment 1
idtrackerai.preprocessing_preview_api - DEBUG - segment 2
__main__.video - INFO - saving video object in /Users/ninatubau/Desktop/session_test/video_object.npy
__main__.video - DEBUG - Video.save(open_multiple_files=False)
idtrackerai_app.base_idtrackerai - DEBUG - call: compute_list_of_blobs
__main__.py_utils - INFO - Setting MKL library to use single thread
__main__.segmentation - INFO - There is only one path, segmenting by frame indices
__main__.py_utils - INFO - Setting MKL library to use multiple threads
idtrackerai_app.base_idtrackerai - DEBUG - call: check_segmentation_consistency
idtrackerai_app.base_idtrackerai - DEBUG - call: save_list_of_blobs_segmented
__main__.video - INFO - saving video object in /Users/ninatubau/Desktop/session_test/video_object.npy
__main__.video - DEBUG - Video.save(open_multiple_files=False)
idtrackerai_app.base_idtrackerai - DEBUG - call: model_area_and_crossing_detector
idtrackerai_app.base_idtrackerai - DEBUG - call: train_and_apply_crossing_detector
__main__.crossing_detector - INFO - Discriminating blobs representing individuals from blobs associated to crossings
__main__.video - INFO - setting path to save crossing detector model
__main__.video - INFO - the folder /Users/ninatubau/Desktop/session_test/crossings_detector has been created
__main__.crossing_detector - INFO - Get individual and crossing images labelled data
__main__.get_crossing_data_set - DEBUG - number of crossing blobs (in get list): 4
__main__.get_crossing_data_set - DEBUG - Not enough crossings where found
__main__.crossing_detector - DEBUG - There are not enough crossings to train the crossing detector
idtrackerai_app.base_idtrackerai - DEBUG - call: generate_list_of_fragments_and_global_fragments
__main__.list_of_blobs - INFO - number_of_individual_fragments, 747
__main__.list_of_blobs - INFO - number_of_crossing_fragments: 4
__main__.list_of_blobs - INFO - total number of fragments: 751
__main__.list_of_fragments - INFO - getting coexisting individual fragments indices
idtrackerai_app.base_idtrackerai - ERROR - max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai_app/base_idtrackerai.py", line 157, in track_video
    if self.step1_pre_processing():
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai_app/base_idtrackerai.py", line 284, in step1_pre_processing
    pre.generate_list_of_fragments_and_global_fragments()
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai/preprocessing_preview_api.py", line 219, in generate_list_of_fragments_and_global_fragments
    self.list_of_global_fragments.compute_maximum_number_of_images()
  File "/[ERROR   ] idtrackerai_app.base_idtrackerai         max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai_app/base_idtrackerai.py", line 157, in track_video
    if self.step1_pre_processing():
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai_app/base_idtrackerai.py", line 284, in step1_pre_processing
    pre.generate_list_of_fragments_and_global_fragments()
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai/preprocessing_preview_api.py", line 219, in generate_list_of_fragments_and_global_fragments
    self.list_of_global_fragments.compute_maximum_number_of_images()
  File "/Users/ninatubau/anaconda3/envs/idtrackerai/lib/python3.6/site-packages/idtrackerai/list_of_global_fragments.py", line 257, in compute_maximum_number_of_images
    self.maximum_number_of_images = max([global_fragment.get_total_number_of_images() for global_fragment in self.global_fragments])
ValueError: max() arg is an empty sequence
